name: Feature Request
description: Suggest an improvement or new capability
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation or pain point are you facing?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature at a high level.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches or workarounds you've tried.

  - type: checkboxes
    id: scope
    attributes:
      label: Scope check
      options:
        - label: This aligns with InvSafe’s undo-safe and audit-focused design
          required: true
